// <auto-generated />
using System;
using Flex.EFSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flex.EFSqlServer.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20231205124856_FlexCmsDbInit")]
    partial class FlexCmsDbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flex.Domain.Entities.SysGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPermissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UrlPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WebsitePermissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_group", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysIndexSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileManage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_FileManage");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Shortcut");

                    b.Property<string>("SiteMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Site_Menu");

                    b.Property<string>("SystemMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_System_Menu");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_systemIndexSet", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontSort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsControllerUrl")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("ShowStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<bool>("isMenu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_menu", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysRoleUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedActionPermission")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_roleurl", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowMultiLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("FilterIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Islock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastLoginIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Mutiloginccode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SaltValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserAvatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserSign")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1560206066204151804L,
                            Account = "webmaster",
                            AddTime = new DateTime(2023, 12, 5, 20, 48, 56, 113, DateTimeKind.Local).AddTicks(2185),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            AllowMultiLogin = true,
                            ErrorCount = 0,
                            Islock = false,
                            LastEditDate = new DateTime(2023, 12, 5, 20, 48, 56, 113, DateTimeKind.Local).AddTicks(2185),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            LastLoginIP = "127.0.0.1",
                            LastLoginTime = new DateTime(2023, 12, 5, 20, 48, 56, 113, DateTimeKind.Local).AddTicks(2185),
                            LoginCount = 0,
                            MaxErrorCount = 0,
                            Mutiloginccode = "7675038.28325281",
                            Password = "5A72A8F355E9A88D03C30778C2770E27",
                            RoleId = "0",
                            RoleName = "超级管理员",
                            SaltValue = "4ad9879fb285407f",
                            UserName = "超级管理员",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesDesc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UrlPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WebsitePermissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_role", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.TestTranscation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_testTransaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
