// <auto-generated />
using System;
using Flex.EFSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flex.EFSqlServer.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20231129111008_FlexCmsDbInit")]
    partial class FlexCmsDbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flex.Domain.Entities.SysGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPermissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UrlPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WebsitePermissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_group", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysIndexSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileManage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_FileManage");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Shortcut");

                    b.Property<string>("SiteMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Site_Menu");

                    b.Property<string>("SystemMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_System_Menu");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_systemIndexSet", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontSort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsControllerUrl")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<long>("ParentID")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShowStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<bool>("isMenu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_menu", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysRoleUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedActionPermission")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_roleurl", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowMultiLogin")
                        .HasColumnType("bit");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("FilterIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Islock")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastLoginIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("Mutiloginccode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_admin", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UrlPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WebsitePermissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_role", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.TestTranscation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_testTransaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
