// <auto-generated />
using System;
using Flex.EFSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flex.EFSqlServer.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20240102063824_updateFieldTableAddModelId")]
    partial class updateFieldTableAddModelId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flex.Domain.Entities.SysColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ColumnImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ExtensionModelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SeoKeyWord")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_column", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysContentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormHtmlString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_contentmodel", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DataPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MenuPermissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UrlPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("WebsitePermissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_group", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysIndexSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileManage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_FileManage");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Shortcut")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Shortcut");

                    b.Property<string>("SiteMenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_Site_Menu");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SystemMenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Index_System_Menu");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_systemIndexSet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            AdminId = 1560206066204151804L,
                            FileManage = "5,6",
                            Shortcut = "",
                            SiteMenu = "171",
                            StatusCode = 1,
                            SystemMenu = "5,158,167,172",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FontSort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsControllerUrl")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("isMenu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "根节点",
                            OrderId = 0,
                            ParentID = 0,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-website",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "站点管理",
                            OrderId = 0,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-slider",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "columnCategory.aspx?SystemID=1",
                            Name = "栏目管理",
                            OrderId = 1,
                            ParentID = 153,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-app",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "columnCategory",
                            Name = "内容管理",
                            OrderId = 2,
                            ParentID = 153,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-wifi",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "webSites.aspx",
                            Name = "网站管理",
                            OrderId = 1,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 67,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-template-1",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "ContentModel",
                            Name = "内容模型",
                            OrderId = 2,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 68,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-export",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "文件管理",
                            OrderId = 3,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 69,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "图片管理系统",
                            OrderId = 0,
                            ParentID = 68,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 70,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-file-b",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "文件管理系统",
                            OrderId = 0,
                            ParentID = 68,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 71,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-template-1",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "PictureCateGory.aspx",
                            Name = "图片分类管理",
                            OrderId = 0,
                            ParentID = 69,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 72,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-picture",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "pictureManage.aspx",
                            Name = "图片管理",
                            OrderId = 0,
                            ParentID = 69,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 73,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-group",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "成员管理",
                            OrderId = 4,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 129,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-component",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "fileCateGory.aspx",
                            Name = "文件分类管理",
                            OrderId = 0,
                            ParentID = 70,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 130,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-file-b",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "fileManage.aspx",
                            Name = "文件管理",
                            OrderId = 0,
                            ParentID = 70,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 131,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-friends",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "管理员管理",
                            OrderId = 0,
                            ParentID = 73,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 132,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-username",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员系统管理",
                            OrderId = 0,
                            ParentID = 73,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 135,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "adminManage.aspx",
                            Name = "账号管理（旧）",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 136,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconnavicon-jsgl",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "RolesPermission/Index",
                            Name = "角色管理",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 137,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员管理",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 138,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员组管理",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 139,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员参数配置",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 140,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-chart",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "访问统计",
                            OrderId = 5,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 141,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconfangwenliang",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "visitsituation.aspx",
                            Name = "统计图表",
                            OrderId = 0,
                            ParentID = 140,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 142,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "pageBox.aspx",
                            Name = "点击分布",
                            OrderId = 0,
                            ParentID = 140,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 143,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "pageBoxs.aspx",
                            Name = "热力图",
                            OrderId = 0,
                            ParentID = 140,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 144,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-set-fill",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "其他配置",
                            OrderId = 6,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 145,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "网站系统配置",
                            OrderId = 0,
                            ParentID = 144,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 146,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "系统配置",
                            OrderId = 0,
                            ParentID = 145,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 147,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconzidian",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "dictionaryManage.aspx?PID=0",
                            Name = "数据字典",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 148,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "adminlog.aspx",
                            Name = "数据日志",
                            OrderId = 0,
                            ParentID = 170,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 149,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconrizhi1",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Menu/Index",
                            Name = "菜单管理",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 150,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "广告管理系统",
                            OrderId = 0,
                            ParentID = 144,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 151,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "广告分类管理",
                            OrderId = 0,
                            ParentID = 150,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 152,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "广告管理",
                            OrderId = 0,
                            ParentID = 150,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 153,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "后台管理系统",
                            OrderId = 0,
                            ParentID = 2,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 154,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "rolesManages.aspx",
                            Name = "角色管理（旧）",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 155,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-link",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "接口管理",
                            OrderId = 100,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 156,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/Index",
                            Name = "菜单接口",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 157,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/DataApiPage",
                            Name = "数据接口",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 158,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "SystemPermission/Index",
                            Name = "系统权限",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 159,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "webConfig.aspx",
                            Name = "网站配置",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 160,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "接口分类",
                            OrderId = 0,
                            ParentID = 155,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 161,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "审核",
                            OrderId = 0,
                            ParentID = 144,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 162,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-cart-simple",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "电商模块",
                            OrderId = 111,
                            ParentID = 1,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 163,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "订单管理",
                            OrderId = 0,
                            ParentID = 162,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 164,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-search",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "在线调查",
                            OrderId = 112,
                            ParentID = 1,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 165,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "投票系统",
                            OrderId = 0,
                            ParentID = 164,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 166,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-form",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "评论管理",
                            OrderId = 113,
                            ParentID = 1,
                            ShowStatus = false,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 167,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconrizhi",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "SystemLog/Index",
                            Name = "系统日志",
                            OrderId = 0,
                            ParentID = 170,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 168,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-username",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Admin/Index",
                            Name = "账号管理",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 169,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/Page",
                            Name = "视图管理",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 170,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "日志模块",
                            OrderId = 0,
                            ParentID = 145,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 171,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "testModel.aspx",
                            Name = "模型测试",
                            OrderId = 0,
                            ParentID = 67,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 172,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "layui-icon-reply-fill",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Admin/SendEmail",
                            Name = "信箱管理",
                            OrderId = 0,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysRoleUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedActionPermission")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_roleurl", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysAdmin", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AllowMultiLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CurrentLoginIP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CurrentLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FilterIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Islock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("LoginLogString")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Mutiloginccode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SaltValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserAvatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserSign")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1560206066204151804L,
                            Account = "webmaster",
                            AddTime = new DateTime(2024, 1, 2, 14, 38, 24, 648, DateTimeKind.Local).AddTicks(7024),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            AllowMultiLogin = true,
                            CurrentLoginIP = "127.0.0.1",
                            CurrentLoginTime = new DateTime(2024, 1, 2, 14, 38, 24, 648, DateTimeKind.Local).AddTicks(7024),
                            ErrorCount = 0,
                            Islock = false,
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            LoginCount = 0,
                            MaxErrorCount = 0,
                            Mutiloginccode = "7675038.28325281",
                            Password = "5A72A8F355E9A88D03C30778C2770E27",
                            RoleId = 0,
                            RoleName = "超级管理员",
                            SaltValue = "4ad9879fb285407f",
                            UserName = "超级管理员",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DataPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MenuPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UrlPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("WebsitePermissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_role", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.TestTranscation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_testTransaction", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApiName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldAttritude")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FieldDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsApiField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsSearch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Validation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_field", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_picture", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysPictureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("AddUser")
                        .HasColumnType("bigint");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("bigint");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_pictureCategory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
