// <auto-generated />
using System;
using Flex.EFSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flex.EFSql.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20240313092401_Initmenudata")]
    partial class Initmenudata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Flex.Domain.Entities.SysColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(4210));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ColumnImage")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("ColumnUrl")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int?>("ExtensionModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsShow")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int?>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("INT");

                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<int?>("ReviewMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SeoKeyWord")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<int?>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_column", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysContentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(5823));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("FormHtmlString")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_contentmodel", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(8743));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ApiName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("FieldAttritude")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("FieldDescription")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<bool?>("IsApiField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsSearch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<bool?>("ShowInTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("Validation")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_field", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 401, DateTimeKind.Local).AddTicks(110));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DataPermission")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("MenuPermissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("UrlPermission")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("WebsitePermissions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_group", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysIndexSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 401, DateTimeKind.Local).AddTicks(2135));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<long>("AdminId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("FileManage")
                        .HasColumnType("NVARCHAR2(8188)")
                        .HasColumnName("Index_FileManage");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Shortcut")
                        .HasColumnType("NVARCHAR2(8188)")
                        .HasColumnName("Index_Shortcut");

                    b.Property<string>("SiteMenu")
                        .HasColumnType("NVARCHAR2(8188)")
                        .HasColumnName("Index_Site_Menu");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("SystemMenu")
                        .HasColumnType("NVARCHAR2(8188)")
                        .HasColumnName("Index_System_Menu");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_systemIndexSet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            AdminId = 1560206066204151804L,
                            FileManage = "5,6",
                            Shortcut = "",
                            SiteMenu = "171",
                            StatusCode = 1,
                            SystemMenu = "5,158,167,172",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 401, DateTimeKind.Local).AddTicks(5270));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("FontSort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Icode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<bool>("IsControllerUrl")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Level")
                        .HasColumnType("INT");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("INT");

                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<bool>("isMenu")
                        .HasColumnType("BIT");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "fontClass",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "根节点",
                            OrderId = 0,
                            ParentID = 0,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-read",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "内容管理",
                            OrderId = 0,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 131,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-friends",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "管理员管理",
                            OrderId = 0,
                            ParentID = 73,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 132,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-username",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员系统管理",
                            OrderId = 0,
                            ParentID = 73,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 136,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconnavicon-jsgl",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "RolesPermission/Index",
                            Name = "角色管理",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 137,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员管理",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 138,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员组管理",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 139,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "会员参数配置",
                            OrderId = 0,
                            ParentID = 132,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 145,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "网站系统配置",
                            OrderId = 0,
                            ParentID = 144,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 146,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "系统配置",
                            OrderId = 0,
                            ParentID = 145,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 147,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconzidian",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "dictionaryManage.aspx?PID=0",
                            Name = "数据字典",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 148,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "adminlog.aspx",
                            Name = "数据日志",
                            OrderId = 0,
                            ParentID = 170,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 149,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconrizhi1",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Menu/Index",
                            Name = "菜单管理",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 153,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "后台管理系统",
                            OrderId = 0,
                            ParentID = 2,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 156,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/Index",
                            Name = "菜单接口",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 157,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/DataApiPage",
                            Name = "数据接口",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 159,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "webConfig.aspx",
                            Name = "网站配置",
                            OrderId = 0,
                            ParentID = 146,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 160,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "接口分类",
                            OrderId = 0,
                            ParentID = 155,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 163,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "订单管理",
                            OrderId = 0,
                            ParentID = 162,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 165,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "投票系统",
                            OrderId = 0,
                            ParentID = 164,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 167,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "iconfont",
                            Icode = "iconrizhi",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "SystemLog/Index",
                            Name = "系统日志",
                            OrderId = 0,
                            ParentID = 170,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 168,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-username",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Admin/Index",
                            Name = "账号管理",
                            OrderId = 0,
                            ParentID = 131,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 169,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "MenuApi/Page",
                            Name = "视图管理",
                            OrderId = 0,
                            ParentID = 160,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 170,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "日志模块",
                            OrderId = 0,
                            ParentID = 145,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 171,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "/system/ContentModel/Index",
                            Name = "模型管理",
                            OrderId = 0,
                            ParentID = 67,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 174,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "/system/WorkFlow/Index",
                            Name = "审核流程图",
                            OrderId = 0,
                            ParentID = 161,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-app",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "/System/columnCategory/Index",
                            Name = "栏目管理",
                            OrderId = 1,
                            ParentID = 153,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-website",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "webSites.aspx",
                            Name = "站点管理",
                            OrderId = 1,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 69,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-picture",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "图片管理",
                            OrderId = 1,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 175,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-export",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "/system/FileManage/Index",
                            Name = "文件管理",
                            OrderId = 1,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-read",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "/System/columnContent/Manage",
                            Name = "内容管理",
                            OrderId = 2,
                            ParentID = 153,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 67,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-template-1",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "内容模型",
                            OrderId = 2,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 73,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-group",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "成员管理",
                            OrderId = 4,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 161,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-chart-screen",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "审核",
                            OrderId = 5,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 144,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-set-fill",
                            IsControllerUrl = true,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "其他配置",
                            OrderId = 6,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 172,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-reply-fill",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "Admin/SendEmail",
                            Name = "信箱管理",
                            OrderId = 7,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        },
                        new
                        {
                            Id = 155,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-link",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "接口管理",
                            OrderId = 100,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 162,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-cart-simple",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "电商模块",
                            OrderId = 111,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 164,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-search",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "在线调查",
                            OrderId = 112,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = true
                        },
                        new
                        {
                            Id = 166,
                            AddTime = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            FontSort = "layui-icon",
                            Icode = "layui-icon-form",
                            IsControllerUrl = false,
                            LastEditDate = new DateTime(2022, 8, 25, 16, 31, 4, 0, DateTimeKind.Unspecified),
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            Level = 0,
                            LinkUrl = "",
                            Name = "评论管理",
                            OrderId = 113,
                            ParentID = 1,
                            ShowStatus = true,
                            StatusCode = 1,
                            Version = 0,
                            isMenu = false
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 401, DateTimeKind.Local).AddTicks(6640));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("ContentId")
                        .HasColumnType("INT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INT");

                    b.Property<string>("FromPathId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsStart")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("MessageCate")
                        .HasColumnType("INT");

                    b.Property<string>("MsgContent")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<long>("MsgGroupId")
                        .HasColumnType("BIGINT");

                    b.Property<int>("ParentId")
                        .HasColumnType("INT");

                    b.Property<string>("RabbitMqQueueName")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int>("RecieveId")
                        .HasColumnType("INT");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("TableName")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("ToPathId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("ToRoleId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("ToUserId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_message", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 402, DateTimeKind.Local).AddTicks(107));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_picture", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysPictureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 401, DateTimeKind.Local).AddTicks(8375));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_pictureCategory", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.SysRoleUrl", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 402, DateTimeKind.Local).AddTicks(2781));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Category")
                        .HasColumnType("INT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("MaxErrorCount")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<bool>("NeedActionPermission")
                        .HasColumnType("BIT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INT");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("RequestType")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("ReturnContent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_roleurl", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysAdmin", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(1749));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool?>("AllowMultiLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<string>("CurrentLoginIP")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime?>("CurrentLoginTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("FilterIp")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<bool>("Islock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("LoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("LoginLogString")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("MaxErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(10);

                    b.Property<string>("Mutiloginccode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("INT");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("SaltValue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("UserAvatar")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("UserSign")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("tbl_core_admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1560206066204151804L,
                            Account = "webmaster",
                            AddTime = new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(1458),
                            AddUser = 1560206066204151804L,
                            AddUserName = "webmaster",
                            AllowMultiLogin = true,
                            CurrentLoginIP = "127.0.0.1",
                            CurrentLoginTime = new DateTime(2024, 3, 13, 17, 24, 1, 400, DateTimeKind.Local).AddTicks(1458),
                            ErrorCount = 0,
                            Islock = false,
                            LastEditUser = 1560206066204151804L,
                            LastEditUserName = "webmaster",
                            LoginCount = 0,
                            MaxErrorCount = 0,
                            Mutiloginccode = "7675038.28325281",
                            Password = "4539390B11E07C307C7A2C4224DF3109",
                            RoleId = 0,
                            RoleName = "超级管理员",
                            SaltValue = "4ad9879fb285407f",
                            UserName = "超级管理员",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Flex.Domain.Entities.System.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 402, DateTimeKind.Local).AddTicks(1525));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DataPermission")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("MenuPermissions")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("RolesDesc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<string>("UrlPermission")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("WebsitePermissions")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_role", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysWorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 406, DateTimeKind.Local).AddTicks(5954));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Introduction")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("WorkFlowContent")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("actDesign")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("actionString")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepDesign")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_workflow", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysWorkFlowAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 402, DateTimeKind.Local).AddTicks(4617));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("actionFromName")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("actionName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("actionPathId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("actionToName")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("conjunctManFlag")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("directMode")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int>("flowId")
                        .HasColumnType("INT");

                    b.Property<string>("orgBossMode")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepFromId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepToCate")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepToId")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_workflowaction", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.sysWorkFlowStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValue(new DateTime(2024, 3, 13, 17, 24, 1, 406, DateTimeKind.Local).AddTicks(7861));

                    b.Property<long?>("AddUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("AddUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("LastEditUser")
                        .HasColumnType("BIGINT");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int?>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(1);

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("avoidFlag")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<int>("flowId")
                        .HasColumnType("INT");

                    b.Property<int>("isStart")
                        .HasColumnType("INT");

                    b.Property<string>("orgMode")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepCate")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepMan")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepOrg")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepPathId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("stepRole")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_workflowstep", (string)null);
                });

            modelBuilder.Entity("Flex.Domain.Entities.TestTranscation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(8188)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(8188)");

                    b.HasKey("Id");

                    b.ToTable("tbl_core_testTransaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
