using Flex.Domain.Entities;
using Flex.Domain.Entities.System;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SkiaSharp;
using System.ComponentModel;
using System.Security.Cryptography;
using System;
namespace Flex.Domain.Config
{
    public class MenuConfig : BaseConfig, IEntityTypeConfiguration<SysMenu>
    {
        public void Configure(EntityTypeBuilder<SysMenu> builder)
        {
            builder.ToTable("tbl_core_menu");
            builder.Property(m => m.Name).HasMaxLength(50);
            builder.Property(m => m.Icode).HasMaxLength(50);
            builder.Property(m => m.ParentID).HasDefaultValue(0);
            builder.Property(m => m.Version).HasDefaultValue(0);
            builder.Property(m => m.LinkUrl).HasMaxLength(200);
            builder.Property(m => m.FontSort).HasMaxLength(200);
            builder.Property(m => m.ShowStatus).HasDefaultValue(true);
            ConfigureSeedData(builder);
            base.ConfigureIntId(builder);
        }
        private void ConfigureSeedData(EntityTypeBuilder<SysMenu> builder)
        {
            builder.HasData(
                new SysMenu {
                    Id = 1,
                    Name = "根节点",
                    Icode = "",
                    ParentID = 0,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                },
                new SysMenu
                {
                    Id = 2,
                    ParentID = 1,
                    Name = "内容管理",
                    Icode = "layui-icon-read",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 131,
                    ParentID = 73,
                    Name = "管理员管理",
                    Icode = "layui-icon-friends",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 132,
                    ParentID = 73,
                    Name = "会员系统管理",
                    Icode = "layui-icon-username",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 136,
                    ParentID = 131,
                    Name = "角色管理",
                    Icode = "iconnavicon-jsgl",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "RolesPermission/Index",
                    FontSort = "iconfont",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 137,
                    ParentID = 132,
                    Name = "会员管理",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 138,
                    ParentID = 132,
                    Name = "会员组管理",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 139,
                    ParentID = 132,
                    Name = "会员参数配置",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 145,
                    ParentID = 144,
                    Name = "网站系统配置",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 146,
                    ParentID = 145,
                    Name = "系统配置",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 147,
                    ParentID = 146,
                    Name = "数据字典",
                    Icode = "iconzidian",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "dictionaryManage.aspx?PID=0",
                    FontSort = "iconfont",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 148,
                    ParentID = 170,
                    Name = "数据日志",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "adminlog.aspx",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 149,
                    ParentID = 146,
                    Name = "菜单管理",
                    Icode = "iconrizhi1",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "Menu/Index",
                    FontSort = "iconfont",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 153,
                    ParentID = 2,
                    Name = "后台管理系统",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 156,
                    ParentID = 160,
                    Name = "菜单接口",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "MenuApi/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 157,
                    ParentID = 160,
                    Name = "数据接口",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "MenuApi/DataApiPage",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 159,
                    ParentID = 146,
                    Name = "网站配置",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "webConfig.aspx",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 160,
                    ParentID = 155,
                    Name = "接口分类",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 163,
                    ParentID = 162,
                    Name = "订单管理",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 165,
                    ParentID = 164,
                    Name = "投票系统",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 167,
                    ParentID = 170,
                    Name = "系统日志",
                    Icode = "iconrizhi",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "SystemLog/Index",
                    FontSort = "iconfont",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 168,
                    ParentID = 131,
                    Name = "账号管理",
                    Icode = "layui-icon-username",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "Admin/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 169,
                    ParentID = 160,
                    Name = "视图管理",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "MenuApi/Page",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 170,
                    ParentID = 145,
                    Name = "日志模块",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 171,
                    ParentID = 67,
                    Name = "模型管理",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "/system/ContentModel/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 174,
                    ParentID = 161,
                    Name = "审核流程图",
                    Icode = "",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "/system/WorkFlow/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 0,
                },
                new SysMenu
                {
                    Id = 4,
                    ParentID = 153,
                    Name = "栏目管理",
                    Icode = "layui-icon-app",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "/System/columnCategory/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 1,
                },
                new SysMenu
                {
                    Id = 6,
                    ParentID = 1,
                    Name = "站点管理",
                    Icode = "layui-icon-website",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "webSites.aspx",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 1,
                },
                new SysMenu
                {
                    Id = 69,
                    ParentID = 1,
                    Name = "图片管理",
                    Icode = "layui-icon-picture",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 1,
                },
                new SysMenu
                {
                    Id = 175,
                    ParentID = 1,
                    Name = "文件管理",
                    Icode = "layui-icon-export",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "/system/FileManage/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 1,
                },
                new SysMenu
                {
                    Id = 5,
                    ParentID = 153,
                    Name = "内容管理",
                    Icode = "layui-icon-read",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    LinkUrl = "/System/columnContent/Manage",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 2,
                },
                new SysMenu
                {
                    Id = 67,
                    ParentID = 1,
                    Name = "内容模型",
                    Icode = "layui-icon-template-1",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 2,
                },
                new SysMenu
                {
                    Id = 73,
                    ParentID = 1,
                    Name = "成员管理",
                    Icode = "layui-icon-group",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 4,
                },
                new SysMenu
                {
                    Id = 161,
                    ParentID = 1,
                    Name = "审核",
                    Icode = "layui-icon-chart-screen",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 5,
                },
                new SysMenu
                {
                    Id = 144,
                    ParentID = 1,
                    Name = "其他配置",
                    Icode = "layui-icon-set-fill",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 6,
                },
                new SysMenu
                {
                    Id = 172,
                    ParentID = 1,
                    Name = "信箱管理",
                    Icode = "layui-icon-reply-fill",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "Admin/SendEmail",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 7,
                },
                new SysMenu
                {
                    Id = 155,
                    ParentID = 1,
                    Name = "接口管理",
                    Icode = "layui-icon-link",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 100,
                },
                new SysMenu
                {
                    Id = 162,
                    ParentID = 1,
                    Name = "电商模块",
                    Icode = "layui-icon-cart-simple",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 111,
                },
                new SysMenu
                {
                    Id = 164,
                    ParentID = 1,
                    Name = "在线调查",
                    Icode = "layui-icon-search",
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 112,
                },
                new SysMenu
                {
                    Id = 166,
                    ParentID = 1,
                    Name = "评论管理",
                    Icode = "layui-icon-form",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 113,
                },
                new SysMenu
                {
                    Id = 176,
                    ParentID = 1,
                    Name = "项目管理",
                    Icode = "layui-icon-component",
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    LinkUrl = "/system/Product/Index",
                    FontSort = "layui-icon",
                    Level = 0,
                    LastEditUser = 1560206066204151804,
                    AddUser = 1560206066204151804,
                    Version = 0,
                    StatusCode = StatusCode.Enable,
                    LastEditUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    OrderId = 113,
                }
          );
        }
    }
}
