using Flex.Domain.Entities;
using Flex.Domain.Entities.System;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SkiaSharp;
using System.ComponentModel;
using System.Security.Cryptography;
using System;

namespace Flex.Domain.Config
{
    public class MenuConfig : BaseConfig, IEntityTypeConfiguration<SysMenu>
    {
        public void Configure(EntityTypeBuilder<SysMenu> builder)
        {
            builder.ToTable("tbl_core_menu");
            builder.Property(m => m.Name).HasMaxLength(50);
            builder.Property(m => m.Icode).HasMaxLength(50);
            builder.Property(m => m.ParentID).HasDefaultValue(0);
            builder.Property(m => m.Version).HasDefaultValue(0);
            builder.Property(m => m.LinkUrl).HasMaxLength(200);
            builder.Property(m => m.FontSort).HasMaxLength(200);
            builder.Property(m => m.ShowStatus).HasDefaultValue(true);
            ConfigureSeedData(builder);
            base.ConfigureIntId(builder);

        }
        private void ConfigureSeedData(EntityTypeBuilder<SysMenu> builder)
        {
            builder.HasData(
                new SysMenu
                {
                    Id = 1,
                    Name = "根节点",
                    Icode = "",
                    ParentID = 0,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 2,
                    Name = "站点管理",
                    Icode = "layui-icon-website",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 4,
                    Name = "栏目管理",
                    Icode = "layui-icon-slider",
                    ParentID = 153,
                    LinkUrl = "columnCategory.aspx?SystemID=1",
                    Level = 0,
                    OrderId = 1,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 5,
                    Name = "内容管理",
                    Icode = "layui-icon-app",
                    ParentID = 153,
                    LinkUrl = "columnCategoryContent.aspx?SystemID=1",
                    Level = 0,
                    OrderId = 2,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 6,
                    Name = "网站管理",
                    Icode = "layui-icon-wifi",
                    ParentID = 1,
                    LinkUrl = "webSites.aspx",
                    Level = 0,
                    OrderId = 1,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 67,
                    Name = "内容模型",
                    Icode = "layui-icon-template-1",
                    ParentID = 1,
                    LinkUrl = "contentModel.aspx",
                    Level = 0,
                    OrderId = 2,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 68,
                    Name = "文件管理",
                    Icode = "layui-icon-export",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 3,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 69,
                    Name = "图片管理系统",
                    Icode = "",
                    ParentID = 68,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 70,
                    Name = "文件管理系统",
                    Icode = "layui-icon-file-b",
                    ParentID = 68,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 71,
                    Name = "图片分类管理",
                    Icode = "layui-icon-template-1",
                    ParentID = 69,
                    LinkUrl = "PictureCateGory.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 72,
                    Name = "图片管理",
                    Icode = "layui-icon-picture",
                    ParentID = 69,
                    LinkUrl = "pictureManage.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 73,
                    Name = "成员管理",
                    Icode = "layui-icon-group",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 4,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 129,
                    Name = "文件分类管理",
                    Icode = "layui-icon-component",
                    ParentID = 70,
                    LinkUrl = "fileCateGory.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 130,
                    Name = "文件管理",
                    Icode = "layui-icon-file-b",
                    ParentID = 70,
                    LinkUrl = "fileManage.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 131,
                    Name = "管理员管理",
                    Icode = "layui-icon-friends",
                    ParentID = 73,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 132,
                    Name = "会员系统管理",
                    Icode = "layui-icon-username",
                    ParentID = 73,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 135,
                    Name = "账号管理（旧）",
                    Icode = "",
                    ParentID = 131,
                    LinkUrl = "adminManage.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 136,
                    Name = "角色管理",
                    Icode = "iconnavicon-jsgl",
                    ParentID = 131,
                    LinkUrl = "RolesPermission/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "iconfont",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 137,
                    Name = "会员管理",
                    Icode = "",
                    ParentID = 132,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 138,
                    Name = "会员组管理",
                    Icode = "",
                    ParentID = 132,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 139,
                    Name = "会员参数配置",
                    Icode = "",
                    ParentID = 132,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 140,
                    Name = "访问统计",
                    Icode = "layui-icon-chart",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 5,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 141,
                    Name = "统计图表",
                    Icode = "iconfangwenliang",
                    ParentID = 140,
                    LinkUrl = "visitsituation.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "iconfont",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 142,
                    Name = "点击分布",
                    Icode = "",
                    ParentID = 140,
                    LinkUrl = "pageBox.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 143,
                    Name = "热力图",
                    Icode = "",
                    ParentID = 140,
                    LinkUrl = "pageBoxs.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 144,
                    Name = "其他配置",
                    Icode = "layui-icon-set-fill",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 6,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 145,
                    Name = "网站系统配置",
                    Icode = "",
                    ParentID = 144,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 146,
                    Name = "系统配置",
                    Icode = "",
                    ParentID = 145,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 147,
                    Name = "数据字典",
                    Icode = "iconzidian",
                    ParentID = 146,
                    LinkUrl = "dictionaryManage.aspx?PID=0",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "iconfont",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 148,
                    Name = "数据日志",
                    Icode = "",
                    ParentID = 170,
                    LinkUrl = "adminlog.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 149,
                    Name = "菜单管理",
                    Icode = "iconrizhi1",
                    ParentID = 146,
                    LinkUrl = "Menu/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "iconfont",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 150,
                    Name = "广告管理系统",
                    Icode = "",
                    ParentID = 144,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 151,
                    Name = "广告分类管理",
                    Icode = "",
                    ParentID = 150,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 152,
                    Name = "广告管理",
                    Icode = "",
                    ParentID = 150,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 153,
                    Name = "后台管理系统",
                    Icode = "",
                    ParentID = 2,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 154,
                    Name = "角色管理（旧）",
                    Icode = "",
                    ParentID = 131,
                    LinkUrl = "rolesManages.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 155,
                    Name = "接口管理",
                    Icode = "layui-icon-link",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 100,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 156,
                    Name = "菜单接口",
                    Icode = "",
                    ParentID = 160,
                    LinkUrl = "MenuApi/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 157,
                    Name = "数据接口",
                    Icode = "",
                    ParentID = 160,
                    LinkUrl = "MenuApi/DataApiPage",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 158,
                    Name = "系统权限",
                    Icode = "",
                    ParentID = 146,
                    LinkUrl = "SystemPermission/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 159,
                    Name = "网站配置",
                    Icode = "",
                    ParentID = 146,
                    LinkUrl = "webConfig.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 160,
                    Name = "接口分类",
                    Icode = "",
                    ParentID = 155,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 161,
                    Name = "审核",
                    Icode = "",
                    ParentID = 144,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 162,
                    Name = "电商模块",
                    Icode = "layui-icon-cart-simple",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 111,
                    ShowStatus = false,
                    isMenu = true,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 163,
                    Name = "订单管理",
                    Icode = "",
                    ParentID = 162,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 164,
                    Name = "在线调查",
                    Icode = "layui-icon-search",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 112,
                    ShowStatus = false,
                    isMenu = true,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 165,
                    Name = "投票系统",
                    Icode = "",
                    ParentID = 164,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 166,
                    Name = "评论管理",
                    Icode = "layui-icon-form",
                    ParentID = 1,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 113,
                    ShowStatus = false,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 167,
                    Name = "系统日志",
                    Icode = "iconrizhi",
                    ParentID = 170,
                    LinkUrl = "SystemLog/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "iconfont",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 168,
                    Name = "账号管理",
                    Icode = "layui-icon-username",
                    ParentID = 131,
                    LinkUrl = "Admin/Index",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 169,
                    Name = "视图管理",
                    Icode = "",
                    ParentID = 160,
                    LinkUrl = "MenuApi/Page",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 170,
                    Name = "日志模块",
                    Icode = "",
                    ParentID = 145,
                    LinkUrl = "",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = true,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 171,
                    Name = "模型测试",
                    Icode = "",
                    ParentID = 67,
                    LinkUrl = "testModel.aspx",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = true,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }, new SysMenu
                {
                    Id = 172,
                    Name = "信箱管理",
                    Icode = "layui-icon-reply-fill",
                    ParentID = 1,
                    LinkUrl = "Admin/SendEmail",
                    Level = 0,
                    OrderId = 0,
                    ShowStatus = true,
                    isMenu = false,
                    IsControllerUrl = false,
                    FontSort = "fontClass",
                    AddTime = "2022/8/25 16:31:04".ToDateTime(),
                    AddUserName = "webmaster",
                    LastEditDate = "2022/8/25 16:31:04".ToDateTime(),
                    LastEditUserName = "webmaster",
                    StatusCode = StatusCode.Enable,
                    Version = 0,
                    AddUser = 1560206066204151804,
                    LastEditUser = 1560206066204151804,
                }
                );
        }
    }
}
